name: Hyperf docker:// 官方用法
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 👇 官方标准：直接使用 Docker 镜像
      - name: 运行 Hyperf 单元测试
        uses: docker://hyperf/hyperf:8.3-alpine-v3.23-swoole
      - name: Composer Update
        run: |
          ls && pwd && php -v && php --ri swoole &&  composer update -o